* Re-Keyboard Developer Notes                                             :TOC:
  - [[#introduction][Introduction]]
  - [[#functionality][Functionality]]
  - [[#references][References]]

** Introduction
This project is experimental (worst than alpha).

Only use this code as an example of an incomplete project.

*** Other related projects
**** Collated list of reMarkable software
Go here first. This site contains a colated list of useful tools for use with
the reMarkable table

See: https://github.com/reHackable/awesome-reMarkable

**** funkey/recept
Project that intercepts and smooths pen strokes via overloading the 'open' system call with LD_PRELOAD.

See: https://github.com/funkey/recept


From this project
#+begin_src ascii
type == 1 && code == 320 && value == 1 -> pen in
type == 1 && code == 320 && value == 0 -> pen out
type == 1 && code == 321 && value == 1 -> eraser in
type == 1 && code == 321 && value == 0 -> eraser out

type == 1 && code == 330 && value == 1 -> pen/eraser down
type == 1 && code == 330 && value == 0 -> pen/eraser up

type == 3 && code == 0 -> value == x
type == 3 && code == 1 -> value == y
type == 3 && code == 24 -> value == pressure
type == 3 && code == 25 -> value == distance
type == 3 && code == 26 -> value == tilt x
type == 3 && code == 27 -> value == tilt y
#+end_src


** Functionality
The reMarkable2 has on-screen buttons in the following locations:

| Button            | Right Hand  | Left Hand   |
|-------------------+-------------+-------------|
| Exit Document     | 20080,15200 | 20080,  800 |
| Menu Open/Close   | 20080,  800 | 20080,15200 |
| Pen Tool          | 18780,  800 | 18780,15200 |
| Pen Options       | 17480,  800 | 17480,15200 |
| Erase Tool        | 16280,  800 | 16280,15200 |
| Select Tool       | 14880,  800 | 14880,15200 |
| Undo              | 13580,  800 | 13580,15200 |
| Redo              | 12280,  800 | 12280,15200 |
| Show Pages        | 4680,  800  | 4680,15200  |
| Show Layers       | 3380,  800  | 3380,15200  |
| Export            | 2080,  800  | 2080,15200  |
| Document Settings | 780,   800  | 780,15200   |
|-------------------+-------------+-------------|

It is possible to remote activate these buttons by writing pen events to
/dev/input/events1. 

** References
*** WACOM Hardware
From 'cat /proc/bus/input/devices' on reMarkable:
#+begin_src ascii
I: Bus=0018 Vendor=056a Product=0000 Version=0031
N: Name="Wacom I2C Digitizer"
P: Phys=
S: Sysfs=/devices/soc0/soc/30800000.aips-bus/30a20000.i2c/i2c-0/0-0009/input/input1
U: Uniq=
H: Handlers=event1 
B: PROP=0
B: EV=b
B: KEY=1c03 0 0 0 0 0 0 0 0 0 0
B: ABS=f000003
#+end_src

*** WACOM Software
See
- https://github.com/linuxwacom/input-wacom/wiki/Analysing-kernel-events
- https://github.com/Wacom-Developer/wacom-device-kit-linux

*** Community Software
**** rmkit
https://github.com/rmkit-dev/rmkit.git

**** Crazy Cow
See:  https://github.com/machinelevel/sp425-crazy-cow

This is another keyboard project for reMarkable.
- Requires a 'service' installation.
- Uses standard keyboards.
- Uses Hersey font.

 

