#!/usr/bin/env bash

maintainer="Paul Schulz <paul@mawsonlakes_org>"
pkgnames=(re-keyboard)
pkgver=0.0.1-1
pkgdesc="Re Keyboard"
url=
section=utils
license=MIT
timestamp=2023-05-15T03:06+00:00

source=("re-keyboard.c"
        "hershey-fonts.c"
        "fonts.h"
       )
sha256sums=("SKIP"
            "SKIP"
            "SKIP"
           )

image=toolchain
#image=base

build() {
    # ${CROSS_COMPILE}gcc -o hershey-fonts.o hershey-fonts.cpp ccow.h
    # ${CROSS_COMPILE}gcc -o re-keyboard.o   re-keyboard.cpp ccow.h
    ${CROSS_COMPILE}gcc -o re-keyboard re-keyboard.c hershey-fonts.c

}

package() {
    install -D -m 755 -t "$pkgdir"/home/root/.local/bin "$srcdir"/re-keyboard
}
